version: "3.8"

services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: postgres # Optional Pre-create a database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes: 
  postgres-data:
